task/urls.py
from django.contrib import admin
from django.urls import path
from task.views import (
    home,
    TaskListView,
    TaskDetailView,
    WorkerDetailView,
    TaskCreateView,
)


urlpatterns = [
    path("", home, name="home"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="task-detail"),
    path("workplace/<int:pk>", WorkerDetailView.as_view(), name="worker-detail")

]

app_name = "task"

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", include("task.urls", namespace="task")),
    path("accounts/", include("django.contrib.auth.urls")),
]

task/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name="workers",
    )


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    deadline = models.DateField()
    is_completed = models.BooleanField()
    priority = models.CharField(
        max_length=1,
        choices=[
            ("U", "Urgent"),
            ("H", "High"),
            ('M', 'Medium'),
            ('L', 'Low'),
        ],
        default="M",
    )
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.CASCADE,
        related_name="tasks",
    )
    assignees = models.ManyToManyField(
        Worker,
        related_name="tasks"
    )

    def __str__(self) -> str:
        return f"{self.task_type} {self.get_priority_display()} priority"

task/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from task.models import Task, Worker

# Create your views here.
def home(request):
    return render(request, "task/home.html")


class TaskListView(generic.ListView):
    model = Task


class TaskDetailView(generic.DetailView):
    model = Task
    queryset = Task.objects.prefetch_related('assignees')

class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task:task-list")
    template_name = "task/task_form.html"

class WorkerDetailView(generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related('tasks')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
      {% include 'includes/sidebar.html' %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
    {% if user.is_authenticated %}
      <li class="list-group-item">User: <a href="{% url 'login'%}">{{ user.get_username }}</a></li>
      <li class="list-group-item"><a href="{% url 'logout'%}">Logout</a></li>
    {% else %}
      <li class="list-group-item"><a href="{% url 'login'%}">Login</a></li>
    {% endif %}
      <li class="list-group-item"><a href="{% url 'task:home' %}">Home</a></li>
    {% if user.is_authenticated %}
      <li class="list-group-item"><a href="{% url 'task:worker-detail' user.id %}">Workplace</a> </li>
    {%endif%}
      <li class="list-group-item"><a href="{% url 'task:task-list'%}">Tasks</a></li>
</ul>

templates/task/home.html
{% extends "base.html" %}
{% block content %}
<h1>Home Page</h1>
<section class="showcase">
    <div class="container-fluid">
        <p>
            Welcome to our Task Manager, designed to streamline your project management and enhance team collaboration. <br>
            Whether you're a Developer, Designer, Project Manager, or QA Specialist, our tool helps you stay organized and efficient. <br> 
            Create, assign, and track tasks effortlessly to ensure timely completion before deadlines. <br>
        </p>
    </div>
</section>


{% endblock %}

templates/task/task_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Detail about task</h1>
Name of the task: {{ task.name }} <br>
Description: {{ task.description }} <br>
Deadline: {{ task.deadline }} <br>
Priority: {{ task.get_priority_display }} <br>
Assigned: <br>
<ul>
    {% for assigne in task.assignees.all %}
    <li>{{assigne}}</li>
    {%endfor%}
</ul>

{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}

{% block content %}
<h1>Create task</h1>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn-primary btn">
</form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}
<h1>All tasks</h1>
<ul>
    {% for task in task_list %}
    <li><a href="{% url 'task:task-detail' task.id %}">{{ task }}</a> {% if not task.is_completed %}Working... {% else %}Done {% endif %}</li>
    {%endfor%}
</ul>

{% endblock %}

templates/task/worker_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Detail about Worker</h1>
<p>{{ worker.username }}</p>
<h2>My tasks</h2>
<ul>
    {% for task in worker.tasks.all %}
    <li>{{ task }}</li>
    {% empty %}
    There is no tasks
    {% endfor %}
</ul>

<br>
<button class="btn btn-primary"><a href="{% url 'task:task-create' %}" style="color: white;">Add tasks</a></button>
{% endblock %}